
#ifndef KEYPAD_CONFIG_H_
#define KEYPAD_CONFIG_H_

#define KEYPAD_U8_COL_PORT DIO_U8_PORTC
#define KEYPAD_U8_ROW_PORT DIO_U8_PORTC

#define KEYPAD_U8_COL_1_PIN  DIO_U8_PIN4
#define KEYPAD_U8_COL_2_PIN  DIO_U8_PIN5
#define KEYPAD_U8_COL_3_PIN  DIO_U8_PIN6
#define KEYPAD_U8_COL_4_PIN  DIO_U8_PIN7


#define KEYPAD_U8_ROW_1_PIN  DIO_U8_PIN0
#define KEYPAD_U8_ROW_2_PIN  DIO_U8_PIN1
#define KEYPAD_U8_ROW_3_PIN  DIO_U8_PIN2
#define KEYPAD_U8_ROW_4_PIN  DIO_U8_PIN3

#define KEYPAD_U8_C1R1 '1'
#define KEYPAD_U8_C1R2 '4'
#define KEYPAD_U8_C1R3 '7'
#define KEYPAD_U8_C1R4 '*'

#define KEYPAD_U8_C2R1 '2'
#define KEYPAD_U8_C2R2 '5'
#define KEYPAD_U8_C2R3 '8'
#define KEYPAD_U8_C2R4 '0'

#define KEYPAD_U8_C3R1 '3'
#define KEYPAD_U8_C3R2 '6'
#define KEYPAD_U8_C3R3 '9'
#define KEYPAD_U8_C3R4 '#'

#define KEYPAD_U8_C4R1 'A'
#define KEYPAD_U8_C4R2 'B'
#define KEYPAD_U8_C4R3 'C'
#define KEYPAD_U8_C4R4 'D'

#endif
